### ISSUE TITLE
How Do I Use This ?

### ISSUE THREAD

**Issue by AgileTomato** [GreenJon902/MemriseBot#1]
Im confused @GreenJon902

**Comment by GreenJon902** [comment]
@AgileTomato
 So it was an unfinished project that I kinda forgot about, I have put in the old version which works fine for me. You just need to run __main__.py, it will fetch the latest chrome driver for you, then you just need to follow the instructions!

**Comment by GreenJon902** [comment]
I have now released a new version that is a lot easier to understand and works better!
